### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by lawrencek1992**
Added Spanish translations. Still needs the following:
-Toggle button needs to say "Español" not Spanish. 
-Some concerns about how to format the name of states (i.e. using the full name of a state vs. the two letter abbreviations). 
-Spanish version of site needs time listed in 24hr format, not 12hr format. 

See comments in the /website/language.js file for more details.

### CODE REVIEW

**Comment by patrickdemers6** [comment]
This looks awesome, thanks! A few requests for you, if you'd be so kind.
- Could you remove the comment at the top of language.js since this issue has been resolved?
- Could you rebase your 56-translations branch with mine. I restructured things a bit last night. There is now a `lang` folder with `english.js` and `spanish.js` to keep things a bit more organized.

I will work on the time format. Is using the state abbreviation not recognizable in Spanish? Although it'd be nice to keep it shortened, we have to make sure it's understandable!

Once we get those changes resolved, I think we should be just about ready. Thank you so much for translating this. I think it's a big step in making the Vaccine Spotter more universal!

**Comment by patrickdemers6** [comment]
FYI @lawrencek1992 I got the time format figured out!

**Comment by lawrencek1992** [comment]
@patrickdemers6 Sorry for the delay. Just got my second dose of the vaccine, and it had me in bed asleep for like a day and a half. Super new to github, and was struggling to learn how to rebase. I instead forked what you currently have, updated the spanish.js file and committed my changes, and then created a pull request with that. I think that should work? If I really need to learn to rebase to get this working, I will, but I wanted to get you the updated file as quickly as I could after laying in bed for so long and letting this go. 

My concern is immigrants. People who are Spanish speakers and have lived here will have learned US postal codes. Immigrants who are new, which is a good chunk of the Spanish-dominant people in the states, aren't going to be familiar with it. Options:
1) I can go replace the {state} with "in your state," which would make sense, like after clicking on Arizona, I'm told there are however many pharmacies being scanned "in your state." 
2) Could leave it as is and hope that after clicking on the name of a state, it's pretty obvious that the two letter abbreviation must refer to THAT state. Probably straight forward for people who are fairly computer savy. But perhaps confusing for people who find basic web navigation to be a new skill and get easily confused. 
3) Switch to using the full names on the Spanish version of the site. If this would be a concern for other languages as well, then perhaps it makes sense and is worth the work to go in and change this (and I honestly don't know if people from other language background would have the same concern, though I'd hazard a guess that the immigrant thing would probably hold constant--i.e. people newer to the country are less likely to know the postal abbreviations). 

Let me know what else I can do/if I really need to figure out the rebasing thing. Thanks for being patient with me being new!

**Comment by patrickdemers6** [comment]
Congrats on getting your second dose! I'm hoping to get my first in the coming weeks. Also--don't feel bad about not feeling the most comfortable with Git. This is my first major contribution on Github as well. I have a lot of experience with GitLab from work but everything is a bit different here on Github. 

I'm going to close this PR and move over to the other one! #2

**Pull request closed without merging**
