### PR TITLE
56 translations

### PR DESCRIPTION
**Pull request by lawrencek1992**
-Removed comments about fixed issues. 
-Put Spanish translations into spanish.js (they were previously in language.js)

### CODE REVIEW

**Comment by patrickdemers6** [comment]
Before I merge, why don't you replace {state} with "in your state". One other request for you: could you update the news? He updated it on the 25th. It should now have date 03/25/21. The main text of it should be:

> <strong>New features!</strong> 🌟 Filter by vaccine type (Moderna, Pfizer, J&amp;J), appointment type (eg, if you only need a 2nd dose), and pharmacy. I know these have been frequently requested features, so I hope these help you in your vaccine quest!

Then the suffix can stay the same. Thank you!

**Comment by patrickdemers6** [comment]
I'm going to get these current changes in. We can get the little things in another PR.

**Comment by lawrencek1992** [comment]
I'll update those things now and do another PR for those things. Probably have it done within the hour.

**Comment by lawrencek1992** [comment]
Just made the PR.

**Pull request merged**
